export const CIVILIZATIONS = [
  "Armenians",
  "Aztecs",
  "Bengalis",
  "Berbers",
  "Bohemians",
  "Britons",
  "Bulgarians",
  "Burgundians",
  "Burmese",
  "Byzantines",
  "Celts",
  "Chinese",
  "Cumans",
  "Dravidians",
  "Ethiopians",
  "Franks",
  "Georgians",
  "Goths",
  "Gurjaras",
  "Hindustanis",
  "Huns",
  "Incas",
  "Italians",
  "Japanese",
  "Jurchens",
  "Khitans",
  "Khmer",
  "Koreans",
  "Lithuanians",
  "Magyars",
  "Malay",
  "Malians",
  "Mapuche",
  "Mayans",
  "Mongols",
  "Muisca",
  "Persians",
  "Poles",
  "Portuguese",
  "Romans",
  "Saracens",
  "Shu",
  "Sicilians",
  "Slavs",
  "Spanish",
  "Tatars",
  "Teutons",
  "Tupi",
  "Turks",
  "Vietnamese",
  "Vikings",
  "Wei",
  "Wu",
] as const;

export const CIVILIZATION_OPTIONS = ["Random", ...CIVILIZATIONS] as const;

export type Civilization = (typeof CIVILIZATION_OPTIONS)[number];

export const civilizationSet = new Set<string>(CIVILIZATION_OPTIONS);
